### ISSUE TITLE
Installation using conda for Python3 and Julia1.3.0

### ISSUE THREAD

**Issue by saeedJahrom** [basnijholt/pfapack#5]
Hello,

I am trying to install pfapack on my local computer for Python3 using "conda install pfapack" and Julia using "Conda.add("pfapack")" but both are showing the following error:

PackagesNotFoundError: The following packages are not available from current channels

Is this package still available on Anaconda repositories? if yes in which repository? I was able to install it using pip but I would rather using this package in Julia as an embedded PyCall function.

Thank you in advance,
Saeed

**Comment by basnijholt** [comment]
I have updated the README.md with: `conda install -c conda-forge pfapack`

I assume this fixes the issue.

If not, I will re-open.

**Comment by saeedJahrom** [comment]
Thank you, it fixed the problem for both Python and Julia.
